# -*- coding: utf-8 -*-
"""Chandrayaan3TDD_Assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xRxOZPcUxvPhvXW0-jY8fm6NYNO65pW-
"""

class space:
    def __init__(self, x, y, z, d):
        self.x = x
        self.y = y
        self.z = z
        self.d = d

    def fr(self):   #Move forward command
        if self.d == "N":
            self.y += 1
        elif self.d == "S":
            self.y -= 1
        elif self.d == "E":
            self.x += 1
        elif self.d == "W":
            self.x -= 1
        elif self.d == "Up":
            self.z += 1
        elif self.d == "Down":
            self.z -= 1

    def bk(self):   #Move backward command
        if self.d == "N":
            self.y -= 1
        elif self.d == "S":
            self.y += 1
        elif self.d == "E":
            self.x -= 1
        elif self.d == "W":
            self.x += 1
        elif self.d == "Up":
            self.z -= 1
        elif self.d == "Down":
            self.z += 1

    def l(self):    #turn left command
        if self.d == "N":
            self.d = "W"
        elif self.d == "S":
            self.d = "E"
        elif self.d == "E":
            self.d = "N"
        elif self.d == "W":
            self.d = "S"
        elif self.d == 'Up' or self.d=="Down":
            if self.previous == 'N':
                self.d = 'W'
            elif self.previous == 'S':
                self.d = 'E'
            elif self.previous == 'E':
                self.d = 'N'
            elif self.previous == 'W':
                self.d = 'S'

    def r(self):     #turn right command
        if self.d == "N":
            self.d = "E"
        elif self.d == "S":
            self.d = "W"
        elif self.d == "E":
            self.d = "S"
        elif self.d == "W":
            self.d = "N"
        elif self.d == 'Up' or self.d=="Down":
            if self.previous == 'N':
                self.d = 'E'
            elif self.previous == 'S':
                self.d = 'W'
            elif self.previous == 'E':
                self.d = 'S'
            elif self.previous == 'W':
                self.d = 'N'

    def u(self):    #up command
        self.previous=self.d
        if self.d == "S":
            self.d = "Down"
        else:
            self.d = "Up"

    def d(self):    #down command
        self.previous=self.d
        self.d = "Down"

    def command_set(self, commands):
        for i in commands:
            if i == "f":
                self.fr()
            elif i == "b":
                self.bk()
            elif i == "l":
                self.l()
            elif i == "r":
                self.r()
            elif i == "u":
                self.u()
            elif i == "d":
                self.d()

        return self.x, self.y, self.z, self.d

a,b,c = 0, 0, 0     #initial values of x y z (starting point)
initial_direction = "N"
commands = ["f", "r", "u", "b", "l"]

space_obj = space(a,b,c, initial_direction)
final_x, final_y, final_z, final_direction = space_obj.command_set(commands)

print("Final Position:", (final_x, final_y, final_z))
print("Final Direction:", final_direction)

